### ISSUE TITLE
Part of Artemis is soehow not displayed at all, I dont know if that is intentional

### ISSUE THREAD

**Issue by CommanderStorm** [ls1intum/Orion#12]
#### To Reproduce

1. Go to a wide Excercise, like PgDP's Woche 06 P01

#### Expected behavior

the Right Part of the Screen should not be wasted that way, but I dont know if that is a byproduct of Artemis' "by desighn"

#### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/26258709/69619634-213dc580-103c-11ea-80e5-6371f353e6c9.PNG)
![Expanded](https://user-images.githubusercontent.com/26258709/69619636-213dc580-103c-11ea-84f6-e52c7f6668cb.PNG)

### Environment

<details><pre>
 - OS: Microsoft Windows [Version 10.0.18363.476]
 - IntelliJ 2019.2
 - Browser chrome
</pre></details>

**Comment by ungaralex** [comment]
Good point. There probably will be an update in the future, which takes care of using the extra space if there is any. Since this is not a high priority problem a.t.m. this might take some time.

**Comment by MDK5** [comment]
Closing since the issue seems to be fixed, Artemis correctly uses the full screen, the Q&A section (which I suspect took up the space) is at the bottom for small screens now.
![fixed](https://user-images.githubusercontent.com/61357727/118333921-e0c25800-b50c-11eb-95b9-feba4faf81b6.png)
