### ISSUE TITLE
Not compatible with IJ 2019.3

### ISSUE THREAD

**Issue by MGoeppl** [ls1intum/Orion#14]
### Describe the bug
I cannot install the plugin bc it is not compatible with IJ 2019.3

#### Expected behavior
Should Install properly

### Environment

<details><pre>
 - OS: macOS 10.15.1
 - IntelliJ [e.g. 2019.3]
 - Browser Safari
 - Version 13.0.3
</pre></details>

#### Output in IntelliJ
<details><pre>
  Plugin 'Artemis Programming Exercise Integration' is incompatible with this installation
</pre></details>

**Comment by ungaralex** [comment]
The support for 2019.3 will be added in the next update 0.3.0.
See #11
