### ISSUE TITLE
Resume Exercise Button invisible

### ISSUE THREAD

**Issue by Progaros** [ls1intum/Orion#16]
### Describe the bug
The "Resume Exercise" button is not displayed

#### To Reproduce

1. Find a Page with the Resume Exercise button
2. Don't find the button

#### Expected behavior
The "Resume Exercise" button should be displayed

#### Screenshots
Artemis:
![Anmerkung 2020-01-03 103623](https://user-images.githubusercontent.com/22076711/71716436-11708880-2e15-11ea-9319-8ffd1241e69a.png)

Chrome:
![Anmerkung 2020-01-03 103645](https://user-images.githubusercontent.com/22076711/71716443-159ca600-2e15-11ea-9b9c-b1c4dc2d5b1a.png)

**Comment by MDK5** [comment]
Fixed by https://github.com/ls1intum/Artemis/pull/1155#issuecomment-581162596
