### ISSUE TITLE
Navigation in an Instructor Project doesn't work.

### ISSUE THREAD

**Issue by nutatuna** [ls1intum/Orion#28]
#### To Reproduce
1. Go to Course Management -> Scroll right -> Exercises
2. Open some random project
3. Try to go back to the Artemis main page by clicking on its logo or Course Overview / Course Management. It doesn't work

#### Screenshots
![Capture](https://user-images.githubusercontent.com/36769488/97789051-c1da2500-1bbd-11eb-9b99-4661f0809987.PNG)

**Comment by MDK5** [comment]
Closing since this appears to be duplicated by #49 which got fixed
