### ISSUE TITLE
Edit in Editor view cannot be left

### ISSUE THREAD

**Issue by FlorianGlombik** [ls1intum/Orion#49]
### Describe the bug

The _Edit in Editor_ view cannot be left once entered.
The breadcrumbs do not work, _Course Overview_ and _Course Management_ cannot be accessed.

#### To Reproduce

1. Login as Editor / Instructor
2. Go to the Course Exercise view
3. Edit a programming exercise with _Edit in IntelliJ_
4. The opened view, which is similar to the _Edit in Editor_ Artemis view cannot be left anymore

#### Expected behavior

The buttons should produce the expected behaviour.

#### Screenshots

![Orion-EditInEditorAlikeViewNotWorking](https://user-images.githubusercontent.com/63976129/118291092-7d6a0300-b4d7-11eb-9146-370e5ac6942c.gif)

### Environment

<details><pre>
 - OS: Windows 10
 - IntelliJ 2021.1.1 ultimate
 - Browser Chrome
 - Orion Version 1.1.2
</pre></details>

#### Error message
<details><pre>
ERROR Error: Uncaught (in promise): TypeError: this.codeEditorContainer is undefined
canDeactivate@https://artemis.ase.in.tum.de/app/10.588f1fdec75a95d68c14.chunk.js:1:1026157
canDeactivate@https://artemis.ase.in.tum.de/app/7.588f1fdec75a95d68c14.chunk.js:2:6725226
subscribe@https://artemis.ase.in.tum.d…
    Angular 18
    _wrapEventTarget trycatch.js:45
    Yn inboundfilters.js:149
    Angular 6
    bn code-editor-instructor-and-editor-orion-container.component.html:27
    Angular 9
    template code-editor-instructor-and-editor-orion-container.component.html:14
    Angular 22
    RxJS 5
    Angular 16
    _wrapEventTarget trycatch.js:45
    Yn inboundfilters.js:150
    handle Angular
    RxJS 20
inboundfilters.js:120:19
</pre></details>

**Comment by MDK5** [comment]
Fixed with Artemis's [#3425](https://github.com/ls1intum/Artemis/pull/3425)
