### ISSUE TITLE
Return button from student exercise view redirects to the current page

### ISSUE THREAD

**Issue by FlorianGlombik** [ls1intum/Orion#50]
### Describe the bug

The return button from the student exercise view redirects to the current page.

#### To Reproduce

1. Open an exercise from the student perspective
2. Click on _Open in IntelliJ_ 
3. Click on the return button in the upper left corner
4. See that you are redirected to the current page

#### Expected behavior

The user should be redirected to the course exercise student view.

#### Screenshots

![Orion-ReturnButtonDoesNotWork](https://user-images.githubusercontent.com/63976129/118293291-cb800600-b4d9-11eb-9ec0-48739365909a.gif)

### Environment

<details><pre>
 - OS: Windows 10
 - IntelliJ 2021.1.1 ultimate
 - Browser Chrome
 - Orion Version 1.1.2
</pre></details>

**Comment by MDK5** [comment]
Fixed with #59
