### ISSUE TITLE
Storing Credentials does not work reliably with runIDE

### ISSUE THREAD

**Issue by MDK5** [ls1intum/Orion#55]
### Describe the bug
Currently Orion uses JCEF's settings to configure it to store credentials locally. However these settings can only be set before the first JCEF client is instantiated. If any other plugin/component happens to also use JCEF and also happens to be loaded before Orion, the settings dont get modified. Such a scenario is given if the opened project has an open markdown file since the markdown viewer also uses JCEF and open files get loaded before Orion.

#### To Reproduce
This bug only appears when running Orion with runIde and could not be observed with installed releases yet.

0. Run Orion with runIde
1. Log in to Artemis via Orion and select to store your credentials
2. Open a markdown file in an Artemis project
3. Restart IntelliJ
4. Orion will ask for credentials to log in, even though they have been stored before
5. Close the markdown file
6. Restart IntelliJ
7. Usually it works again (unless your setup has some other plugin using JCEF)

#### Solution
The only solution I can think of would be to not reflect into the library at all but instead transfer the session tokens via the connectors and store it somewhere in the global registry or the secure password registry and write them back in the local storage on startup using javascript.

**Comment by GunniBusch** [comment]
Still no auto login on MacOS. Windows works fine.

**Comment by GunniBusch** [comment]
#100 Should fix it
