### ISSUE TITLE
Submit Button is not showing

### ISSUE THREAD

**Issue by KingSeybro** [ls1intum/Orion#71]
### Describe the bug
After starting an exercise, I get the "In IntelliJ öffnen" button, which successfully opens the project, but after that I don't get a "Submit" button, it stays as the "In IntelliJ öffnen" button.

#### To Reproduce
1. Open IntelliJ
2. Login to your Artemis Account
3. Select exercise and start it
4. Open exercise in IntelliJ
5. Work on exercise
6. See no "Submit" button

#### Expected behavior
Instead of the "In IntelliJ öffnen" button it should show the "Submit" button

### Environment

<details><pre>
 - Windows 10 Pro
 - IntelliJ 2021.2.3
 - Orion 1.2.0
</pre></details>

#### Additional context
A student encountered the problem first, so I tested it on my machine

**Comment by MDK5** [comment]
Thanks for submitting this issue! I tried to reproduce the bug on my setup, but failed to do so; for me the submit button correctly shows if the correct exercise project is opened. Could you please contact me on the TUM Zulip or the Artemis Slack to discuss this further?

**Comment by MDK5** [comment]
In the meeting the issues was not reproducable. Closing this now, if the issue reappears please reopen it.
