### ISSUE TITLE
Highlight student's changes in an assessment

### ISSUE THREAD

**Issue by MDK5** [ls1intum/Orion#77]
### Is your feature request related to a problem?
When assessing a submission, it sometimes gets difficult to determine what the student actually coded and what was already present in the template.

### Describe the solution you'd like
Artemis solves this problem by highlighting the student's changes to the template, similar to a git commit. Such a solution should also be integrated into the assessment editor of Orion.

### Describe alternatives you've considered
Instead tutors can use the git plugin to review the changes, but this can only be done independent of the assessment and would force them to swap editors.

### Additional context
I already experimented with IntelliJs diff-editors, but failed to find a solution to access the gutter of a diff editor, making it impossible to display the buttons to add new inline comments. The code with more explanaition can be found [here](https://github.com/ls1intum/Orion/blob/9b916d351bf99681e0e566a64a4b45db8750ded2/src/main/java/de/tum/www1/orion/ui/assessment/OrionEditorProvider.kt#L37).

Alternatively one could look into not using IntelliJ's diff functions but instead calculate the diff themselves with the same algorithm used by Artemis and then find a way to simply highlight specific lines in the editor.

**Comment by Kroko-fant** [comment]
implemented in #90
