### ISSUE TITLE
Publish new version to Marketplace to support IntelliJ 2022

### ISSUE THREAD

**Issue by derkalaender** [ls1intum/Orion#82]
### Is your feature request related to a problem?
Users of IntelliJ 2022 versions can't download the plugin via the Marketplace function because the version there is heavily outdated.

### Describe the solution you'd like
Release a new version on the IntelliJ Marketplace

### Describe alternatives you've considered
Downloading the orion.zip via Actions Artifacts and installing manually. This is tedious and not user friendly.

### Additional context
-/-

**Comment by MaximIgenbergs** [comment]
Maybe actually update? Its been a long time for such a minor update (that probably doesnt even require any new code)...
