### ISSUE TITLE
Back button in the webview sometimes not working any more

### ISSUE THREAD

**Issue by ungaralex** [ls1intum/Orion#9]
### Describe the bug

The back button in the webview stops working after some time (no clear pattern so far). 

#### To Reproduce

Cannot reproduce so far. Seems to be happening spontaneously

#### Expected behavior

You should be able to navigate to the previous page if there is a visible back button in the Artemis UI

### Environment

<details><pre>
 - OS: macOS Mojave 10.14.6
 - Version: 0.2.4
</pre></details>

**Comment by nutatuna** [comment]
This bug seems to be related to JavaFx runtime. It works fine on JCEF.
